# Generated by Django 3.0.1 on 2020-01-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon_url', models.FileField(null=True, upload_to='')),
                ('price_per_year', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('coverage_id', models.IntegerField()),
                ('what_happened', models.CharField(max_length=200)),
                ('date_time_happened', models.DateTimeField(null=True)),
                ('time_happened', models.BigIntegerField(null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('damaged_part', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('company_id', models.IntegerField(null=True)),
                ('starting_at', models.DateTimeField(blank=True, null=True)),
                ('ending_at', models.DateTimeField(blank=True, null=True)),
                ('video_mile', models.FileField(blank=True, null=True, upload_to='')),
                ('video_vehicle', models.FileField(blank=True, null=True, upload_to='')),
                ('image_mile', models.FileField(blank=True, null=True, upload_to='')),
                ('image_vehicle', models.FileField(blank=True, null=True, upload_to='')),
                ('state', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('car_type_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=200)),
                ('state', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200, null=True)),
                ('car_type_id', models.IntegerField(blank=True, null=True)),
                ('world_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('namespace', models.CharField(max_length=200, null=True)),
                ('confirmation_hash', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_id', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=200, null=True)),
                ('endpoints_http', models.CharField(max_length=200, null=True)),
                ('endpoints_mqtt', models.CharField(max_length=200, null=True)),
                ('endpoints_uploader', models.CharField(max_length=200, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('grant_type', models.CharField(max_length=200, null=True)),
                ('href', models.CharField(max_length=200, null=True)),
                ('owner_id', models.CharField(max_length=200, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
                ('scope_1', models.CharField(max_length=200, null=True)),
                ('scope_2', models.CharField(max_length=200, null=True)),
                ('pay_state', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
