# Generated by Django 3.0.1 on 2020-01-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
