# Generated by Django 3.0.1 on 2020-01-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0002_user_pay_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coverage',
            name='image_mile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coverage',
            name='image_vehicle',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
