# Generated by Django 3.0.1 on 2019-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0003_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='company_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='end_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='start_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='state',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='video_mile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='video_vehicle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
