# Generated by Django 3.0.1 on 2019-12-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0004_auto_20191230_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
