# Generated by Django 3.0.1 on 2019-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0005_auto_20191230_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='video_mile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='video_vehicle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
