# Generated by Django 3.0.1 on 2019-12-29 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0008_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='user_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
