# Generated by Django 3.0.1 on 2019-12-29 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0009_claim_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='date_time_happened',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='time_happened',
            field=models.IntegerField(),
        ),
    ]
