# Generated by Django 3.0.1 on 2019-12-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0014_fileuploadtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='video_mile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='video_vehicle',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
