# Generated by Django 3.0.1 on 2019-12-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0015_auto_20191231_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverage',
            old_name='end_at',
            new_name='ending_at',
        ),
        migrations.RenameField(
            model_name='coverage',
            old_name='start_at',
            new_name='starting_at',
        ),
        migrations.AlterField(
            model_name='coverage',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
