# Generated by Django 3.0.1 on 2019-12-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRentalApp', '0017_auto_20191231_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='icon_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
